language: php

php:
  - 5.6

env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=array
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

sudo: false

before_script:
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit