language: php

php:
  - 5.6

env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=base64:Nau2kXiToK8o4nsUE76kc0CEMAGiaEYixDageVl+cVs=
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=array
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

sudo: false

before_script:
  - mkdir bootstrap/cache
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script: vendor/bin/phpunit